### ISSUE TITLE
90% Test coverage in ambry.cli

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry#10]
Expand the tests in test_warehouse to produce a minimum of 90% test coverage for each of the files in the directory ambry.cli. Develop these tests in tests/test_cli.py

NOTE: Some of this work will involve improving tests, some will involve removing code. Be sure to ask if it looks like code is old, useless or never used.

**Comment by suprotkin** [comment]
I'll take it

**Comment by ericbusboom** [comment]
Ok, you can assign yourself to issues to claim them.
