### ISSUE TITLE
u() Vs unicode()

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry#100]
There are a few places in the code (https://github.com/CivicKnowledge/ambry/blob/ambry1.0/ambry/bundle/files.py#L223) where:

    return u(',').join(u(e).replace(',', '\,') for e in v)

The ``u(e)`` is really required because e can be either a string or an int, and if it is a string, the replace needs to be run. But in python2, u() does it's own replacement first, which fails when e is an int. 

What should actually be there is something that is equivalent to uniccode() in python2, and str() in python3

**Comment by nmb10** [comment]
What about:
```python
from six impor u
temp = lambda v: u(',').join(u('{}').format(e).replace(',', '\,') for e in v)
```

Some test:
python2
```python
# list of strings
>>> temp(['a,b']), type(temp(['a,b']))
(u'a\\,b', <type 'unicode'>)

# list of ints
>>>  temp([1, 2]), type(temp([1, 2]))
(u'1,2', <type 'unicode'>)
```

python3
```python
# list of strings
>>> temp(['a,b']), type(temp(['a,b']))
('a\\,b', <class 'str'>)

# list of ints
>>>  temp([1, 2]), type(temp([1, 2]))
('1,2', <class 'str'>)
```
Is it required behaviour? This method is described [here](https://github.com/CivicKnowledge/ambry/blob/ambry1.0/doc/DEVEL-README.md#to-write-python2python3-compatible-code) and is 2to3 compatible (that means code formatted this way will not be changed by 2to3 util.)

**Comment by ericbusboom** [comment]
> On Sep 15, 2015, at 2:06 AM, Kazbek <notifications@github.com> wrote:
> 
> What about:
> 
> from
>  six impor u
> temp 
> = lambda v: u(',').join(u('{}').format(e).replace(',', '\,') for e in v)

Ah, yes, format() would do fine. 

eric. 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org
