### ISSUE TITLE
Search test improvements

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry#108]
The search tests should cover the case of using a Sqlite file on disk, not just the in-memory database, because as per issue #107, there are material differences.

**Comment by nmb10** [comment]
I tryed to use file db while testing. All tests passed. Can you give the whole session of the wrong behaviour of the search system?

**Comment by ericbusboom** [comment]
The Regression test for issue #107 triggered the problem, ambry/test/test_library/regression/issue_107.py, but the issue is fixed now. 

This issue addresses the lack of  tests in the main test suite for a test of library.search(). So, there should be some additional functional tests of the search system that use the library.search(), rather than going to the underlying index, and very importantly, it should do it for these types of databases and backends: Whoosh, postgres, Sqlite in memory, Sqlite on disk.

**Comment by nmb10** [comment]
Done.
