### ISSUE TITLE
Improve PEP8 compliance

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry#11]
Eliminate all of the PEP8 warnings produced by flake8, when run on the ambry/ambry directory. 

Currently, most of these issues are: 

E501 line too long 
F401 ... imported but unused

Afterwards, make sure all of the test still run.

**Comment by suprotkin** [comment]
I'll take it

**Comment by ericbusboom** [comment]
> On Apr 24, 2015, at 3:20 AM, Roman Suprotkin <notifications@github.com> wrote:
> 
> I'll take it
> 

OK, I’ll assign it to you. You are now a member of the Ambry Github team, so you can just assign the issues to yourself. 

eric.

**Comment by ericbusboom** [comment]
One thing, though; While I much prefer to take standards as is, I really, really don't like the PEP8 line width of 79 chars. I've been using 120 char, and don't really see any downsides to it. So, I'd prefer not to reformat the code to that. 

However, I did use autopep at one point, and it did re-format to 80 char, so there are a lot of cases where lines are wrapped. I've been undoing the cases of this that I most hate.
