### ISSUE TITLE
Sources: Change 'url' and 'generator' to 'ref'

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry#127]
There are three values in the DataSource table for referencing the object that produces rows: url, ref and generator. These three should be combined into 'ref'. 

Then, the 'urltype'  should be changed 'reftype'

**Comment by nmb10** [comment]
What are the choices for `ref` field?
What are the choices for `reftype` field?

**Comment by ericbusboom** [comment]
``Ref`` can be anything. It is  a URL for files with a URL, a partition name or partition id for partitions,  a Google Doc ID for google docs. For generator objects, it is the generator class name. 

The ``reftype`` value is not strongly defined, but there are some values for it in orm.source.DataSourceBase#is_downloadable, which is used to determine if the file should be downloaded during ingest. Then, bundle.bundle.Bundle#_ingest has a special check for a reftype of 'generator'.

The values in orm.source.DataSourceBase#is_downloadable should be moved to a class constant. Currently they are hard coded in the method. 

However, I thought I had assigned this one to myself. I've already done part of it, so I'll take you off and finish it up.
