### ISSUE TITLE
Update setup.py test commands

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry#138]
We now have a re-organized test environment, described at: 

https://github.com/CivicKnowledge/ambry/blob/master/doc/README.testing.md

However, it isn't quite finished: we need new test commands. The commands should be:

- python setup.py test --bundle # or -b
- python setup.py test --unit # or -u
- python setup.py test --functional # or -f
- python setup.py test --regresison # or -r 
- python setup.py test --all # or -a, for all of the above
- python setup.py test # defaults to --functional

Additionally, all of the command should take these mutually exclusive options: 
- --sqlite  or -s. Test with a sqlite database
- --postgres or -p Test with a postgres database. 

As described in the [test README](https://github.com/CivicKnowledge/ambry/blob/master/doc/README.testing.md), these options will set the `AMBRY_TEST_DB` environmental variable to select which type of database to use.

**Comment by nmb10** [comment]
Done.

**Comment by nmb10** [comment]
> Additionally, all of the command should take these mutually exclusive options:
    --sqlite or -s. Test with a sqlite database
    --postgres or -p Test with a postgres database.

I'm a developer, and I want to run both. How should I do that?

**Comment by ericbusboom** [comment]
> On Nov 11, 2015, at 4:42 AM, Kazbek <notifications@github.com> wrote:
> 
> Additionally, all of the command should take these mutually exclusive options:
> --sqlite or -s. Test with a sqlite database
> --postgres or -p Test with a postgres database.
> 
> I'm a developer, and I want to run both. How should I do that?

Run the command twice. 

They don’t actually have to be mutually exclusive; you could detect which options are selected, and then have the test program arrange for multiple runs. So, if you select both, it would run the tests twice. 

eric. 


------------------------------------------------------------------------------------------------------------------------
Civic Knowledge                                                                Data for community development
Eric Busboom, eric@civicknowledge.com,  (619) 363 2607         http://civicknowledge.com

**Comment by nmb10** [comment]
Now tests can run over both databases.
```python
python setup.py test --postgres --sqlite
```
In such a case all tests run on postgres, then all tests run on sqlite.
