### ISSUE TITLE
Send email if tests fail

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry#141]
Add a feature to the setup.py test command to specify an email address to send the test results to if the test fails. The email should contain both the full run of the test as well as all of the environmental variables. 

This feature will primarily be used in automating testing inside Docker containers.

**Comment by nmb10** [comment]
Done. Parameter is described here - https://github.com/CivicKnowledge/ambry/blob/develop/doc/DEVEL-README.md#getting-broken-tests-notifications-to-email
