### ISSUE TITLE
Find a new Stemmer

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry#145]
The search system, in ambry/library/search_backends/base.py uses nltk for stemming. Importing nltk interferes with web requests in sub processes: 

http://stackoverflow.com/questions/30766419/python-child-process-silently-crashes-when-issuing-an-http-request

Determine if there is a way to replace the stemmer with another one.

**Comment by nmb10** [comment]
Can you give an example of code to reproduce an error? I tryed code from stackoverflow question and did not get any error.

**Comment by nmb10** [comment]
Can't reproduce.
