### ISSUE TITLE
Unit tests modify repository files.

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#15]
Run tests:
```bash
python -m unittest discover
```

Find modified:
```bash
git status | grep modified
        modified:   test/bundles/example.com/geography/meta/schema.csv
        modified:   test/bundles/testbundle/meta/doc.yaml
        modified:   test/bundles/testbundle/meta/documentation.html
        modified:   test/bundles/testbundle/meta/schema.csv
```

**Comment by ericbusboom** [comment]
The doc.yaml and documentation.html can be removed from github, but the schema.csv is harder to deal with. The test bundle needs to be part of the test code, and the system modifies the schema when it builds files. 

However, it would be sensible to move schema.csv to schema-source.csv, and copy it to schema.csv at the start of the tests.

**Comment by ericbusboom** [comment]
Actually, move the schema.csv file to "protoschema.csv" and then copy it over. protoschema.csv is the name used for the file in the ambry.bundle.loader.LoaderBundle.
