### ISSUE TITLE
test/bundlefiles/ambry.yaml necessity.

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#193]
Do we need it? I found only one mention in the test_multiprocessing.py file. But this file contains broken tests only.

**Comment by ericbusboom** [comment]
> On Feb 14, 2016, at 7:24 AM, Kazbek <notifications@github.com> wrote:
> 
> Do we need it? I found only one mention in the test_multiprocessing.py file. But this file contains broken tests only.

I think it is obsolete. 

eric. 


----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by nmb10** [comment]
Deleted.
