### ISSUE TITLE
ImportError: cannot import name NotASummaryName

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#39]
```bash
python -m unittest test_library.Test.test_s3_push
```
http://pastebin.com/wCYY4jLN

**Comment by ericbusboom** [comment]
Sync with the Civicknowledge develop branch. I've added a requirements.txt dependency to geoid 0.0.7 ( so you'll have to pip obgrade to that. )

**Comment by nmb10** [comment]
Updating geoid fixed it.
