### ISSUE TITLE
No delimiter parameter in row_spec for converting csv file

### ISSUE THREAD

**Issue by Gudinya** [CivicKnowledge/ambry#88]
Could not read csv file with TAB delimiter

**Comment by ericbusboom** [comment]
Review the source for CSvBundle. There is a TsvBundle version.

Eric

--------------------------------------------------------------------------------------------------
Eric Busboom, CEO, Clarinova                                            (858) 386-4134

**Comment by Gudinya** [comment]
Yes, I missed it, but did you see https://github.com/Gudinya/ambry_bundles, I use TAB delimiter there with new source code, may be it's more flexible specify the delimiter for csv file in build.yaml than use another class?

**Comment by suprotkin** [comment]
For now it would be better to add row_gen_for_source method to your Bundle class

https://gist.github.com/ericbusboom/8f7b6f3373b7eb833d9c#file-row_gen_for_source

**Comment by Gudinya** [comment]
There two types of csv file in one archive and they could be read by one class.

**Comment by ericbusboom** [comment]
Can one of you post a URL to a source file that is triggering this issue? I'll need it for testing.

**Comment by Gudinya** [comment]
archive: http://data.medicare.gov/views/bg9k-emty/files/K2mijv-Kwa3BxIvmpxh3ZYiFHcn_15Cd4WbvhBb9m3s?filename=HHCompare_Revised_FlatFiles.zip

file with TAB: HHC_SOCRATA_MSR_DT_RNG.csv
file with comma: HHC_SOCRATA_NATIONAL.csv
