### ISSUE TITLE
Rebuild Full Text Search

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry#89]
In Ambry 0.3, full text search is implemented in Whoosh, which requires substantial additional time to load and probably doesn't scale well. This system should be re-worked to use the library database more directly and employ database-suppled full-text search where possible. 

The new system should basically follow the model of the existing systems, in terms of function. See ambry/ambry/library/search.py for the current implementation. The new system should add:

* Plugable back end. Be able to use: Sqlite or Postgres builtin FTS for development and bundle building environments, Elasticsearch in production for the main search system. 

In the current system, there are two schemas: 
- DatasetSchema, used for datasets, partitions, tables and columns
- IdentifierSchema, used for GVIDS  ( Geo versioned ids ) that reference geographic regions. 

 (These two schemas are disjoint although related. The IdentifierSchema only has about 4,000 entries, so it could be done in memory. )

The current system produced two types of search documents, both of which are stored in the DatasetSchema:

- dataset_doc
- partition_doc

For this issue, the simplest solution would be to re-implement the search interface object so it can take a configurable back-end, which much include: 

- Sqlite
- Postgres
- Whoosh
- Elastic search

Most likely, for Postgres and Sqlite, there would be a new, custom table for the search documents, in the same database as the library, but not necessarily managed by Sqlalchemy. 

The search system must be updated when:
- A bundle is added to the library
- A bundle is prepared ( bundle.do_prepare )
- A bundle is installed
- A bundle is removed

For the first two cases, only the Dataset document is added to the search index. There are no partitions yet. 

For the third case, The dataset and all partitions are added. 

There should be no need for any explicit indexing, although there should be a way to re-index. 

The Identities schema should be automatically indexed when the library is created. 

Configuration  for the back end should be done in the ambry.yaml file, under service.search. The configuration is accessed via ambry.run.RunConfig#service. 

The configuration should not be required, with the default search system being to use the library database, if the library is postgres or sqlite. Configuration is only required to use ElasticSearch or Whoosh.

**Comment by nmb10** [comment]
First level of config should be tied to the type of library, If you have a Sqlite library, the default should be SQLite, with an option for Whoosh. If the library is Postgres, the default should be Postgres, with an option for ElasticSearch.

However, Whoosh is primarily for bootstrapping from the current system. Once the Sqlite version is working well and fast, there is probably no need for Whoosh. ( And if Sqlite isn’t capable, we’ll stick with Whoosh. )

So, the only real choice would be between Postgres and ElasticSearch, in production. To use elastic search, you’d have to set up an entry in the ‘services’ section of the ambry config, probably ‘services.search’. That could be the trigger for using ElasticSearch.

So, the config rules would be:

- If services.search exists, use ElasticSearch
- If library is postgres, use postgres
- If library is Sqlite, use Sqlite. ( Or Whoosh, if Sqlite isn’t capable enough )
- If in a test env, and Whoosh is configured, use Whoosh.

**Comment by nmb10** [comment]
PostgreSQL backend implemented.
