### ISSUE TITLE
90% Test coverage in ambry.warehouse

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry#9]
Expand the tests in test_warehouse to produce a minimum of 90% test coverage for each of the files in the directory ambry.warehouse. Develop these tests in tests/test_warehouse.py

NOTE: Some of this work will involve improving tests, some will involve removing code. Be sure to ask if it looks like code is old, useless or never used.

**Comment by Gudinya** [comment]
Hi, I want to assign the issue to myself. Can you add me to the github team? I'm already fork the project.

**Comment by ericbusboom** [comment]
Hi Gudinya, 

I submitted the invitation on github about 20 minutes ago, to the CivicKnowledge “Contract Developers” team.  I can see Ambry forked in the account I invited, so it must be yours. Let me know if you can’t find it, and I’ll try it again. 

eric.

**Comment by Gudinya** [comment]
Everything is ok, thank you!

2015-04-27 19:09 GMT+03:00 Eric Busboom <notifications@github.com>:

>
> Hi Gudinya,
>
> I submitted the invitation on github about 20 minutes ago, to the
> CivicKnowledge "Contract Developers" team. I can see Ambry forked in the
> account I invited, so it must be yours. Let me know if you can't find it,
> and I'll try it again.
>
> eric.
>

**Comment by Gudinya** [comment]
How do you think, issue is ready to be closed?

**Comment by ericbusboom** [comment]
No, not yet. The coverage is only at 64%. 

To get the coverage:

    $ coverage run setup.py test
    $ coverage html --include='*/ambry/ambry/warehouse/*'
    $ open htmlcov/index.html 

Some of the coverage deficit is due to some new functions -- stream_table() and install_indexed_table(), and there are a few that should be removed. Let me remove the ones that really aren't needed, and then you can write tests for the rest.

**Comment by Gudinya** [comment]
ок

**Comment by ericbusboom** [comment]
Actually, can you start with these changes?

- delete method Warehouse.info()
- delete method Warehouse.extract_all()
- Write test for Warehouse. extract_table()
- Write test for Warehouse.has()
- Write test for Warehouse.remove()
- Write test for Warehouse.load_insert()

**Comment by Gudinya** [comment]
Ok, but I have no idea for now how to test Warehouse.has()
But anyway I will look more carefully and try to find out what it is about

**Comment by ericbusboom** [comment]
Warehouse.has(): Just install a partition, then call Warehouse.has() with the id or name of the partition. Usually, that is p.identity.vid for the versioned id number, or p.identity.vname.

**Comment by Gudinya** [comment]
Thanks!

**Comment by Gudinya** [comment]
HI, after install GDAL tests start fall with message "ParseError: Partition reference not resolved to a bundle: 'source-dataset-subset-variation-geot1' in manifest '/media/sf_ambry/ambry/test/manifests/test.ambry'  for library sqlite:////tmp/ambry-manifest-test/library.db"     I have checked /tmp/ambry-manifest-test/library.db it's empty. Do you know what it is ?

**Comment by ericbusboom** [comment]
> On May 28, 2015, at 1:19 AM, Gudinya <notifications@github.com> wrote:
> 
> HI, after install GDAL tests start fall with message "ParseError: Partition reference not resolved to a bundle: 'source-dataset-subset-variation-geot1' in manifest '/media/sf_ambry/ambry/test/manifests/test.ambry' for library sqlite:////tmp/ambry-manifest-test/library.db" I have checked /tmp/ambry-manifest-test/library.db it's empty. Do you know what it is ?

Actually, let’s skip the GDAL tests. I’m planning on removing most of it from the system, except for import, which can be tested separately. 

eric. 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by Gudinya** [comment]
Ok, I'll skip GDAL tests, but I found out that partitions in manifest file have end on "-geo" to pass that exception, but I get another exception.
