### ISSUE TITLE
Improved Row Intuition

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry#90]
The Row Intuiter reads rows from a dataset and tries to classify rows as comment, header or data. This is an important process for use with Excel files, which often start with a title and comments, so the data header does not appear on the first line, as is expected. 

In Ambry 1.0, the row intuiter will be a Pipe (ambry.bundle.etl.pipeline.Pipe) that reads rows from an upstream pipe to perform the classification, and writes just the header and data to the downstreams. 

The Row Intuiter pipe will also store the line numbers for the various classifications, so they can saved in a source record and used later in the build process. 

Here is an example of a table that needs classification: 

|  |         |        |            |               |                |                   |
|--:|:-------------------------|:-------|:-----------|:--------------|:---------------|:------------------|
| 0 | Renter Costs             |        |            |               |                |                   |
| 1 | This is a header comment |        |            |               |                |                   |
| 2 |                          |        |            |               |                |                   |
| 3 |                          |        | renter     |               | owner          |                   |
| 4 | id                       | gvid   | cost_gt_30 | cost_gt_30_cv | cost_gt_30_pct | cost_gt_30_pct_cv |
| 5 | 1.0                      | 0O0P01 | 1447.0     | 13.6176070905 | 42.2481751825  | 8.272140707       |
| 6 | 2.0                      | 0O0P03 | 5581.0     | 6.235932071   | 49.2803532009  | 4.93336930536     |
| 7 | 3.0                      | 0O0P05 | 525.0      | 17.6481586483 | 45.2196382429  | 13.2887199931     |
| 8 | 4.0                      | 0O0P07 | 352.0      | 28.061964578  | 47.4393530997  | 17.3833286874     |

To classify rows, use the following algorithm. 

First, break the dataset into three sections:
- The first 20 lines ( Header section ) 
- The last 20 lines ( Footer section ) 
- A random sample ( 200 lines or so ) of the middle lines. ( Data section ) 

The Intuiter pipe should run through all rows, storing lines in the tree sections. Process the lines when the upstream source produces a StopIteration. 

First, use a sample of the data section to extract a pattern for the data, in terms of width ( number of columns ) and type ( python data type).

The output from this step will be a set of pattern lists, which have the same width as a row, and where each element is a tuple that holds data types that were seen in that column. For instance: 

[ (int), (int), (int|float), (str), (str|int), (None, str) ]

To determine the type of a cell, attempt to convert the the cell, which starts as a str or None, into other types. First try converting to float, then to int. ( For int, check that int(v) == round(float(v),0) )

( Could possibly use the existing type intuiter to buld the patterns: ambry.bundle.etl.intuit.TypeIntuiter )

After computing a data pattern, create a header pattern that has the same length as the  data patterns, but each cell is (str|None)

Create a comment pattern that consists of strings in the first two rows, and nothing after that: 

[ (str|None), (str|None), (None), (None) ... ]

Then run the data pattern over the  header and footer section to find the start and end lines of the data. This classifies rows as data. 

Then run header pattern over the header section to classify header lines, with the additional constraint that at least 40% of the cells must match as str. ( Or some other % ) This is because there can be multiple header lines -- such as lines 3 and 4 in the example -- and some of the header lines will have names for every column ( 4 ) and some not (3). 

Finally, run the comment pattern, which should match lines like (1) and (2) in the example. 

To produce the random sample of data rows:
- Create a 200 row buffer. 
- Store rows 20 to 220 in the buffer. 
- After row 220, each additional row has a random chance to replace one of the rows in the buffer. For each row, if random.random() < . 01, replace line buffer[randint(0,200)]

**Comment by ericbusboom** [comment]
I've added a new method for flowing data through the system, implemented in ambry/bundle/etl/pipeline.py.  The Row Intuiter must be implemented as a pipe segment, which basically just invovles inheriting from Pipe and implementing __iter__().

**Comment by nmb10** [comment]
Keep comments in a RowIntuiter property - they’ll get picked up in the final routine. Keep all of the comment rows, as a list. Join the cells of each row into a single string, then each row separately in the list.

**Comment by nmb10** [comment]
Use another algorithm to find data pattern:

1) After row 20, start constructing / updating the row_data pattern.
2) Process at least L1 ( ? 500 ) rows, incorporating them into the row_data pattern,
3) After L1 rows, keep track of the number of changes to the pattern on each update.
4) If there have been more than L2 ( ? 500 ) rows with no updates to the pattern, stop updating. When there is a change to the pattern, reset the counter back to L2.
5) Also stop if there are a very large number of changes, particularly if the new row would introduce a lot of Nones. That means you’ve hit the footer comments.

That means the minimum number of rows processed would be at least 20+L1+L2, as long as the file has more than 20+L1+L2+20 lines.

**Comment by nmb10** [comment]
Done.
