### ISSUE TITLE
Deletions in metadata dicts not propagated to database 

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry#93]
If you load in a bundle.yaml file with : 

    requirements:
        a: a
        b: b

and then change the bundle.yaml file to: 

    requirements:
        a: a
        c: c

The database will have a,b and c, but it should have only a and c.

**Comment by nmb10** [comment]
What steps should I do to repeat exactly that case?

**Comment by ericbusboom** [comment]
The test case should edit the bundle.yaml to be the first example, run Bundle.sync_in(), edit to get the second case, run Bundle.sync_in(),  then load the bundle.yaml file directly as YAML and check the result.

**Comment by nmb10** [comment]
Done. Tests - https://github.com/CivicKnowledge/ambry/blob/ambry1.0/test/test_metadata/regression/test_ambry_93.py .
